name: Continuous integrations for project

on: push

env:
  CARGO_TERM_COLOR: always

jobs: 
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build project
        run: cargo build
      - name: upload binary file artifact
        uses: actions/upload-artifact@v3
        with: 
          name: xnft-tool
          path: /target/debug/xnft-tool

  test: 
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      run: cargo test
  
  release: 
    name: Release project
    runs-on: ubuntu-latest
    needs: build